theme: jekyll-theme-midnight
title: Bill Crosbie - ITI game development
description: I am an associate professor of game development at [Raritan Valley CC](http://www.raritanval.edu) and I work as an adjunct instructor and curriculum developer with the Infomration Technology and Informatics degree
